package sipa.bem;

import java.awt.image.BufferedImage;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static sipa.bem.Koneksi.buatkoneksi;

/**
 *
 * @author 2201010700_Ayudevi
 * tgl: 2024-06-19
 */
public class jForm1 extends javax.swing.JFrame {
    DefaultTableModel TM = new DefaultTableModel();
    /**
     * Creates new form jForm1
     */
    public jForm1() throws SQLException {
        initComponents();
        jTable1.setModel(TM);
        TM.addColumn("NIM");
        TM.addColumn("Nama_Peminjam");
        TM.addColumn("Organisasi");
        TM.addColumn("Kondisi");
        TM.addColumn("Nama_Barang");
        TM.addColumn("Jumlah");
        
        List_All();
        kosongkanfrom();
        loadphoto ("");
    
    }
    
    private void loadphoto (String idx){
        String nopic = "img/nopic.png";
        String ph = "img/"+idx+".png";
        System.out.println(ph);
        BufferedImage phototeman = loadIMG.loadImage(ph);
        if (phototeman == null) {
            phototeman = loadIMG.loadImage(nopic);
        }
        ImageIcon iconphoto = new ImageIcon(phototeman);
        photo. setIcon (iconphoto);
    }
    
    private void List_All () throws SQLException{
        TM.getDataVector().removeAllElements();
        TM.fireTableDataChanged();
        
        
        Connection cnn = buatkoneksi();
        if( !cnn.isClosed() ){
            String sql = "SELECT * FROM peminjaman_alat;";
            PreparedStatement PS = cnn. prepareStatement(sql);
            ResultSet rs = PS.executeQuery();
            while (rs.next()){
                Object[] dta = new Object[6];
                dta [0] = rs.getString("NIM");
                dta [1] = rs.getString("Nama_Peminjam");
                dta [2] = rs.getString("Organisasi");
                dta [3] = rs.getString("Kondisi");
                dta [4] = rs.getString("Nama_Barang");
                dta [5] = rs.getString("Jumlah");
                TM.addRow(dta);
            }
        }
    }
    
    private void StoreData() throws SQLException{
        Connection cnn = buatkoneksi();
        String NIM = txNim.getText();
        String NM = txNama.getText();
        String OR = txOrganisasi.getText();
        String KN = txKondisi.getText();
        String NB = txNamaBarang.getText();
        String JML = txJumlah.getText();
        if(!cnn.isClosed()){
           PreparedStatement PS = cnn.prepareStatement("INSERT INTO peminjaman_alat(NIM, Nama_Peminjam, Organisasi, Kondisi, Nama_Barang, Jumlah)VALUES(?,?,?,?,?,?);");
           PS.setString(1, NIM);
           PS.setString(2, NM);
           PS.setString(3, OR);
           PS.setString(4, KN);
           PS.setString(5, NB);
           PS.setString(6, JML);
           PS.executeUpdate();
        }
    }
    
    private void UpdateData() throws SQLException{
         Connection cnn = buatkoneksi();
        if(!cnn.isClosed()){
            PreparedStatement PS = cnn. prepareStatement("UPDATE peminjaman_alat SET Nama_Peminjam=?, Organisasi=?, Kondisi=?, Nama_Barang=?, Jumlah=? WHERE NIM=?");
            PS.setString(1, txNama.getText());
            PS.setString(2, txOrganisasi.getText());
            PS.setString(3, txKondisi.getText());
            PS.setString(4, txNamaBarang.getText());
            PS.setString(5, txJumlah.getText());
            PS.setString(6, txNim.getText());
            PS.executeUpdate ();
            cnn.close();
        }
    }
    
    private void DestroyData() throws SQLException{ 
        Connection cnn = buatkoneksi();
        if(!cnn.isClosed()){
            PreparedStatement PS = cnn. prepareStatement ("DELETE FROM peminjaman_alat WHERE NIM=?");
            PS.setString(1, txNim.getText());
            PS.executeUpdate();
            cnn.close();
        }
    }
    
    private void kosongkanfrom(){
        txNim.setText("");
        txNama.setText("");
        txOrganisasi.setText("");
        txKondisi.setText("");
        txNamaBarang.setText("");
        txJumlah.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txNim = new javax.swing.JTextField();
        txNama = new javax.swing.JTextField();
        txOrganisasi = new javax.swing.JTextField();
        txKondisi = new javax.swing.JTextField();
        txNamaBarang = new javax.swing.JTextField();
        txJumlah = new javax.swing.JTextField();
        btnBaru = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnTutup = new javax.swing.JButton();
        photo = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Sistem Informasi Peminjaman Alat Bem ");

        jLabel2.setText("NIM");

        jLabel3.setText("Nama Peminjam");

        jLabel4.setText("Organisasi");

        jLabel5.setText("Kondisi");

        jLabel6.setText("Nama Barang");

        jLabel7.setText("Jumlah  ");

        txNim.setText("jTextField1");

        txNama.setText("jTextField2");

        txOrganisasi.setText("jTextField3");

        txKondisi.setText("jTextField4");

        txNamaBarang.setText("jTextField5");

        txJumlah.setText("jTextField6");

        btnBaru.setText("Baru");
        btnBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaruActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NIM", "Nama_Peminjam", "Organisasi", "Kondisi", "Nama_Barang", "Jumlah"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Formulir Peminjaman Alat Bem");

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnTutup.setText("Tutup Form");
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });

        photo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBaru)
                        .addGap(28, 28, 28)
                        .addComponent(btnUbah)
                        .addGap(28, 28, 28)
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTutup))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel7))
                                        .addGap(104, 104, 104)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txJumlah)
                                            .addComponent(txKondisi, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txOrganisasi, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txNamaBarang, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txNama)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txNim, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(30, 30, 30)))
                        .addComponent(photo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(167, 167, 167))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(195, 195, 195))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txOrganisasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txKondisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(photo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBaru)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus)
                    .addComponent(btnTutup))
                .addGap(0, 151, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaruActionPerformed
        if (btnBaru.getText().equals("Baru")){
            btnBaru.setText("Simpan");
            btnTutup.setText("Batal");
            kosongkanfrom();
            jTable1.setEnabled(false);
        }else {
            btnBaru.setText ("Baru");
            btnTutup.setText("TutupForm");
            jTable1.setEnabled(true);
            try {
                StoreData();         
                List_All();
            } catch (SQLException ex) {
                Logger.getLogger(jForm1.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnBaruActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        txNim.setText (jTable1.getValueAt(jTable1.getSelectedRow(),0).toString());
        txNama.setText(jTable1.getValueAt( jTable1.getSelectedRow(),1).toString());
        txOrganisasi.setText(jTable1.getValueAt( jTable1.getSelectedRow(),2).toString());
        txKondisi.setText(jTable1.getValueAt( jTable1.getSelectedRow(),3).toString());
        txNamaBarang.setText(jTable1.getValueAt( jTable1.getSelectedRow(),4).toString());
        txJumlah.setText(jTable1.getValueAt( jTable1.getSelectedRow(),5).toString());
        loadphoto (txNim.getText());
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        try {
            UpdateData();
            List_All();
            JOptionPane.showMessageDialog(this,"Data telah diupdate");
        } catch (SQLException ex) {
            Logger.getLogger(jForm1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int jwb = JOptionPane.showOptionDialog(this , "Yakin akan menghapus data " +txNim.getText()+"?", "Hapus Data ", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE, null, null, null);
        if(jwb == JOptionPane.YES_OPTION){
            try{
            DestroyData();
            List_All();
        }   catch (SQLException ex) {
                Logger.getLogger(jForm1.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        if(btnTutup.getText().equals("TutupForm")){
            dispose();
        }else{
            btnTutup.setText("TutupForm");
            btnBaru.setText("Baru");
        }
    }//GEN-LAST:event_btnTutupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new jForm1().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(jForm1.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaru;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTutup;
    private javax.swing.JButton btnUbah;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel photo;
    private javax.swing.JTextField txJumlah;
    private javax.swing.JTextField txKondisi;
    private javax.swing.JTextField txNama;
    private javax.swing.JTextField txNamaBarang;
    private javax.swing.JTextField txNim;
    private javax.swing.JTextField txOrganisasi;
    // End of variables declaration//GEN-END:variables
}
